# Disable some built-in rules
config:
  no-trailing-spaces: false
  no-multiple-blanks: false

# Fix any fixable errors
fix: true

# Ignore files referenced by .gitignore (only valid at root)
gitignore: true

# Define glob expressions to use (only valid at root)
# globs:
#   - "!*bout.md"

# Define glob expressions to ignore
ignores:
  - "docs/docs/api/**/**"

# Disable progress on stdout (only valid at root)
noProgress: false

# Show found files on stdout (only valid at root)
showFound: true

