[files]
extend-exclude = ["docs/docs/api/**", "docs/bun.lock"]
ignore-hidden = true
ignore-files = true
ignore-dot = true
ignore-vcs = true
ignore-global = true
ignore-parent = true

[default]
binary = false
check-filename = true
check-file = true
unicode = true
ignore-hex = true
identifier-leading-digits = false
locale = "en"
extend-ignore-identifiers-re = []
extend-ignore-words-re = ["(?i)requestor","(?i)indentity","(?i)encrypter","(?i)seeked","(?i)generater","(?i)policys","NDA*"]
extend-ignore-re = ["(?Rm)^.*//\\s*spellchecker:disable-line$"]
pass_filenames = false
enable = true
