/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  documentationSidebar: [
    { type: "autogenerated", dirName: "docs/product_docs" },
  ],
  developerSidebar: [
    { type: "autogenerated", dirName: "docs/developer_docs" },
  ],
  fullApiSidebar: [
    {
      type: 'category',
      label: 'GraphQL Definitions',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "api/graph-api"
        },
      ],
    },
    {
      type: 'category',
      label: 'OpenAPI Specification',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "api/rest-api"
        },
      ],
    },
  ],

};

export default sidebars;