/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  baseModules: [
    { type: "autogenerated", dirName: "platform/basics" },
  ],
  complianceManagement: [
    { type: "autogenerated", dirName: "platform/compliance-management" },
  ],
  complianceAutomation: [
    { type: "autogenerated", dirName: "platform/compliance-automation" },
  ],
  riskManagement: [
    { type: "autogenerated", dirName: "platform/risk-management" },
  ],
  trustCenter: [
    { type: "autogenerated", dirName: "platform/trust-center" },
  ],
  auditPreparation: [
    { type: "autogenerated", dirName: "platform/audit" },
  ],
  developing: [
    { type: "autogenerated", dirName: "developers/developing" },
  ],
  security: [
    { type: "autogenerated", dirName: "developers/security" },
  ],
  integrations: [
    { type: "autogenerated", dirName: "developers/integrations" },
  ],
  restAPISidebar: [
    {
      type: "autogenerated",
      dirName: "api/rest-api",
    },
  ],
  graphAPISidebar: [
    {
      type: "autogenerated",
      dirName: "api/graph-api"
    },
  ],
};

export default sidebars;