/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  platform: [
    "platform/overview",
    "platform/audit/index",
    "platform/basics/overview",
    "platform/compliance-management/overview",
    "platform/compliance-automation/overview",
    "platform/policy-and-procedure-management/policies",
    "platform/risk-management/overview",
    "platform/trust-center/overview",
    "platform/integrations/integrations/index",
    "platform/glossary/index"
  ],
  developers: [
    "developers/overview",
    {
      type: "link",
      label: "Developing",
      href: "developing/startup"
    },
    {
      type: "link",
      label: "Integrations",
      href: "integrations/overview"
    },
    {
      type: "link",
      label: "Security",
      href: "/docs/category/authentication-methods-1"
    },
    {
      type: "link",
      label: "Deployment",
      href: "deployment/overview"
    },
    {
      type: "link",
      label: "Documentation Contributions",
      href: "contributing/references"
    },

  ],
  platformMain: [
    { type: "autogenerated", dirName: "platform" },
  ],
  developerMain: [
    { type: "autogenerated", dirName: "developers" },
  ],
  basic: [
    { type: "autogenerated", dirName: "platform/basics" },
  ],
  platformIntegrations: [
    {
      type: 'category',
      label: 'Integrations',
      link: { type: 'doc', id: 'platform/integrations/integrations/index' },
      items: [
        {
          type: 'doc',
          id: 'platform/integrations/slack',
        },
        {
          type: 'doc',
          id: 'platform/integrations/github',
        },
      ]
    },
  ],
  complianceManagement: [
    { type: "autogenerated", dirName: "platform/compliance-management" },
  ],
  complianceAutomation: [
    { type: "autogenerated", dirName: "platform/compliance-automation" },
  ],
  policies: [
    { type: "autogenerated", dirName: "platform/policy-and-procedure-management" },
  ],
  risks: [
    { type: "autogenerated", dirName: "platform/risk-management" },
  ],
  audit: [
    {
      type: 'category',
      label: 'Audit Preparation',
      link: { type: 'doc', id: 'platform/audit/index' },
      items: [
        {
          type: 'doc',
          id: 'platform/audit/firms',
        },
        {
          type: 'doc',
          id: 'platform/audit/gapanalysis',
        },
        {
          type: 'category',
          label: 'Risk Analysis',
          link: { type: 'doc', id: 'platform/audit/riskanalysis/overview' },
          items: ['platform/audit/riskanalysis/overview', 'platform/audit/riskanalysis/riskmitigation', 'platform/audit/riskanalysis/riskassessment'],
        }
      ],
    },
  ],
  riskAnalysis: [
    { type: "autogenerated", dirName: "platform/audit/riskanalysis" },
  ],
  trustCenter: [
    { type: "autogenerated", dirName: "platform/trust-center" },
  ],
  glossary: [
    { type: "autogenerated", dirName: "platform/glossary" },
  ],
  deployment: [
    { type: "autogenerated", dirName: "developers/deployment" }
  ],
  contributing: [
    { type: "autogenerated", dirName: "developers/contributing" }
  ],
  developing: [
    { type: "autogenerated", dirName: "developers/developing" }
  ],
  integrations: [
    { type: "autogenerated", dirName: "developers/integrations" }
  ],
  security: [
    { type: "autogenerated", dirName: "developers/security" }
  ],
  restAPISidebar: [
    {
      type: "autogenerated",
      dirName: "api/rest-api",
    },
  ],
  graphAPISidebar: [
    {
      type: "autogenerated",
      dirName: "api/graph-api"
    },
  ],
};

export default sidebars;